"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import type { Route } from "next";
import {
  Dumbbell,
  Utensils,
  Moon,
  Droplets,
  Scale,
  Target,
  BarChart2,
  Settings,
  Activity,
  ListChecks,
  Calendar,
} from "lucide-react";
import { cn } from "@/lib/utils/cn";
import { ROUTES, APP_NAME } from "@/constants";

const NAV_ITEMS = [
  { href: ROUTES.DASHBOARD, label: "Overview", icon: Activity, exact: true },
  { href: ROUTES.WORKOUTS, label: "Workouts", icon: Dumbbell },
  { href: ROUTES.EXERCISES, label: "Exercises", icon: ListChecks },
  { href: ROUTES.NUTRITION, label: "Nutrition", icon: Utensils },
  { href: ROUTES.SLEEP, label: "Sleep", icon: Moon },
  { href: ROUTES.WATER, label: "Water", icon: Droplets },
  { href: ROUTES.WEIGHT, label: "Weight", icon: Scale },
  { href: ROUTES.GOALS, label: "Goals", icon: Target },
  { href: ROUTES.PHASES, label: "Phases", icon: Calendar },
  { href: ROUTES.ANALYTICS, label: "Analytics", icon: BarChart2 },
] as const;

const BOTTOM_ITEMS = [{ href: ROUTES.SETTINGS, label: "Settings", icon: Settings }] as const;

function NavItem({
  href,
  label,
  icon: Icon,
  exact = false,
}: {
  // Route type is generated by Next.js typedRoutes — `string & {}` satisfies it
  // while still accepting any valid route constant from ROUTES.
  href: string & {};
  label: string;
  icon: React.ElementType;
  exact?: boolean;
}) {
  const pathname = usePathname();
  const isActive = exact ? pathname === href : pathname.startsWith(href);

  return (
    <Link
      href={href as Route}
      className={cn(
        "flex items-center gap-3 rounded-lg px-3 py-2 text-sm font-medium transition-colors",
        isActive
          ? "bg-indigo-50 text-indigo-700 dark:bg-indigo-950/50 dark:text-indigo-300"
          : "text-gray-700 hover:bg-gray-100 hover:text-gray-900 dark:text-gray-400 dark:hover:bg-gray-800 dark:hover:text-gray-100",
      )}
    >
      <Icon className="h-4 w-4 shrink-0" />
      {label}
    </Link>
  );
}

export function Sidebar() {
  return (
    <aside className="hidden w-60 flex-col border-r border-gray-200 bg-white lg:flex dark:border-gray-700 dark:bg-gray-900">
      {/* Logo */}
      <div className="flex h-16 items-center border-b border-gray-200 px-5 dark:border-gray-700">
        <Link href={ROUTES.DASHBOARD} className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-600">
            <Dumbbell className="h-4 w-4 text-white" />
          </div>
          <span className="font-bold text-gray-900 dark:text-gray-100">{APP_NAME}</span>
        </Link>
      </div>

      {/* Main nav */}
      <nav className="flex flex-1 flex-col gap-1 overflow-y-auto px-3 py-4">
        {NAV_ITEMS.map((item) => (
          <NavItem key={item.href} {...item} />
        ))}
      </nav>

      {/* Bottom nav */}
      <div className="border-t border-gray-200 px-3 py-4 dark:border-gray-700">
        {BOTTOM_ITEMS.map((item) => (
          <NavItem key={item.href} {...item} />
        ))}
      </div>
    </aside>
  );
}
